language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_install:
  - npm install karma karma-jasmine karma-phantomjs-launcher karma-junit-reporter karma-coverage
  - npm install coveralls --save
  - export PATH="./node_modules/karma/bin:$PATH"

before_script:
  - mvn help:active-profiles

script: ./run_tests.sh

after_success:
  - ls coverage
  - cat ./coverage/PhantomJS\ 1.9.7\ \(Linux\)/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  - mvn jacoco:report coveralls:jacoco